In [1]:
import pandas as pd

In [3]:
dataset=pd.read_csv(r"C:\Users\LENOVO\Downloads\housing.csv",encoding='latin')

In [4]:
dataset.head(3)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7

In [6]:
dataset.rename(columns={'MEDV':'House_price'},inplace=True)

In [7]:
dataset.head(3)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,House_price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7

In [14]:
dataset.shape

(506, 14)

In [8]:
input_data=dataset.iloc[:,:-1]
output_data=dataset["House_price"]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.25)

In [18]:
x_train.shape, y_train.shape

((379, 13), (379,))

In [19]:
x_test.shape, y_test.shape

((127, 13), (127,))