In [20]:
import pandas as pd

In [21]:
dataset = pd.read_csv(r"C:\\Users\\LENOVO\\Downloads\\IndividualDetails11.csv",encoding='latin1')
dataset.head(7)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
5,5,NaN,03-03-2020,69,M,Jaipur,Italians,Rajasthan,Italy,Recovered,03-03-2020,Travelled from Italy
6,6,NaN,04-03-2020,55,NaN,Gurugram,Italians,Haryana,Italy,Recovered,29-03-2020,Travelled from Italy

In [22]:
dataset.isnull().sum()

id                        0
government_id         25185
diagnosed_date            0
age                   25836
gender                22869
detected_city         25832
detected_district      6984
detected_state            0
nationality           25473
current_status            0
status_change_date      402
notes                  1335
dtype: int64

In [23]:
dataset["gender"]=dataset["gender"].fillna(dataset["gender"].mode()[0])

In [39]:
dataset

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,M,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,M,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,NaN,22-04-2020,NaN,M,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28178,28179,NaN,24-04-2020,NaN,M,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28179,28180,NaN,24-04-2020,NaN,M,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28180,28181,NaN,25-04-2020,NaN,M,NaN,Nagpur,Maharashtra,NaN,Hospitalized,NaN,Correction for district count
28181,28182,NaN,25-04-2020,NaN,M,NaN,NaN,Maharashtra,NaN,Hospitalized,NaN,Correction for district count

In [40]:
dataset["nationality"]=dataset["nationality"].fillna(dataset["nationality"]).mode()[0],dataset

ValueError: Length of values (2) does not match length of index (28182)

In [26]:
en_data=dataset[["gender","current_status"]]

In [27]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28182 entries, 0 to 28181
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender_F                     28182 non-null  bool
 1   gender_M                     28182 non-null  bool
 2   current_status_Deceased      28182 non-null  bool
 3   current_status_Hospitalized  28182 non-null  bool
 4   current_status_Migrated      28182 non-null  bool
 5   current_status_Recovered     28182 non-null  bool
dtypes: bool(6)
memory usage: 165.3 KB

In [28]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
ohe=OneHotEncoder()
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 56364 stored elements and shape (28182, 6)>

In [30]:
ohe=OneHotEncoder()
ohe.fit_transform(en_data).toarray()

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.]], shape=(28182, 6))

In [31]:
ohe=OneHotEncoder()
ar=ohe.fit_transform(en_data).toarray()

In [32]:
pd.DataFrame(ar,columns=["gender_F ","gender_M "," current_status_Deceased ","current_status_Hospitalized","current_status_Migrated","current_status_Recovered"])

,gender_F,gender_M,current_status_Deceased,current_status_Hospitalized,current_status_Migrated,current_status_Recovered
0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...
28177,0.0,1.0,0.0,1.0,0.0,0.0
28178,0.0,1.0,0.0,1.0,0.0,0.0
28179,0.0,1.0,0.0,1.0,0.0,0.0
28180,0.0,1.0,0.0,1.0,0.0,0.0
28181,0.0,1.0,0.0,1.0,0.0,0.0

In [33]:
ohe=OneHotEncoder(drop="first")
ar=ohe.fit_transform(en_data).toarray()
ar

array([[0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       ...,
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]], shape=(28182, 4))

In [34]:
dataset()

TypeError: 'DataFrame' object is not callable